### ISSUE TITLE
Current page number displays "NaN" when you click on next/previous page on Nodes page table view 

### ISSUE THREAD

**Issue by Clariceco** [planetdecred/pdanalytics#45]
On Nodes page, when you switch to the table view and you click on Next/Previous page, the current page number changes to "NaN" as seen below:
![Screenshot from 2021-10-23 20-55-18](https://user-images.githubusercontent.com/66803475/138569758-4e31f67d-eada-4121-8906-99d417c3f7b7.png)
However, when I refresh, the number shows correctly

**Comment by mkingori** [comment]
Kindly provide more information on where I can trace the bug. A link on the scenario will help

**Comment by monsa00** [comment]
https://analytics.planetdecred.org/nodes?view-option=table

If you click on next page the current page displays "NaN"

**Comment by crux25** [comment]
> https://analytics.planetdecred.org/nodes?view-option=table
> 
> If you click on next page the current page displays "NaN"
> 
> ![image](https://user-images.githubusercontent.com/66281245/132887023-b129dac0-dbcd-41d5-acf8-f2ae18cf038b.png)

I can't reproduce this. What browser are you running on?

**Comment by monsa00** [comment]
Chrome 93
