### ISSUE TITLE
Proposals Module - Refinement

### ISSUE THREAD

**Issue by Clariceco** [planetdecred/pdanalytics#47]
- click does not display charts fix coming in on PR

- Issue not only displaying - failing to pull down list proposals 

- Not getting the data - part of current upcoming PR = page currently broken

- Enhancements chart to make a cleaned up proposal face - quite glitchy not our highest priority but still nice. 
- Try to make any changes problem with javascript on exchange rate view

- Last link for VSPs page is glitching everything I select on left side data disappears 

- Some data was pulling from Dcr data website - check on that data source is there a difference in data from old stake pulls and new stake pulls and what is the difference in displaying on new page, it is drawing a flat line when issue with data being drawn or no data collection. Maybe better displayed differently not have a line at all

- Look into why we lost data collection, hard to do when interface is as buggy as it is

**Comment by devchoplife** [comment]
All sub-issues have been merged which renders this issue redundant.
